### ISSUE TITLE
Feature request: consolidate function

### ISSUE THREAD

**Issue by TI-ZA** [cyber-republic/elastos-light-wallet#10]
add consolidate function if too many utxo, api for utxo number /api/v1/asset/utxos/(String:`addr`)

**Comment by MButcho** [comment]
Implemented in https://github.com/MButcho/elastos-light-wallet/releases/tag/v1.0.0-RC49-MB should be merged soon.

**Comment by TI-ZA** [comment]
added in v1.0.0
