### ISSUE TITLE
Feature request: Add select active votes button on voting

### ISSUE THREAD

**Issue by TI-ZA** [cyber-republic/elastos-light-wallet#11]
Add a button that pre-selects active voting nodes for convenience

**Comment by MButcho** [comment]
"Select Active" or "Select Voted" button:
![Select_Active](https://user-images.githubusercontent.com/41790777/83678181-9b4b9a00-a5dd-11ea-807c-aa7aa76a96e4.png)

**Comment by MButcho** [comment]
Implemented
