### ISSUE TITLE
Bug: Display bug after vote tx

### ISSUE THREAD

**Issue by MButcho** [cyber-republic/elastos-light-wallet#20]
After vote confirmed on Ledger, this is how the screen looks like:
![Display-bug1](https://user-images.githubusercontent.com/41790777/83680956-f8e1e580-a5e1-11ea-8d3e-e33b4102b90e.png)

The message on the bottom (not the green popup on top) shouldn't be there. If it's needed don't post whole tx address, just first 5 characters + .... + last 5 characters instead) and add "space" after to separate votes "22/93"

**Comment by MButcho** [comment]
Also on some transactions I receive following screen
![photo_2020-06-03_21-36-03](https://user-images.githubusercontent.com/41790777/83681240-67bf3e80-a5e2-11ea-8705-b1a18e473585.jpg)

**Comment by MButcho** [comment]
The bug could be due to multiple sessions at the same time connecting to Ledger.  Review the background sessions to Ledger. It should be enough to connect to Ledger on wallet start, login and then on demand when sending tx.

**Comment by coranos** [comment]
The ledger software doesn't support any sort of 'background session checking', the connection is established to get the public key, then reestablished to sign the tx.

So my advice is not to click so fast, and be patient, so you don't cause the error.
