### ISSUE TITLE
Feature Request: Spending Password

### ISSUE THREAD

**Issue by TI-ZA** [cyber-republic/elastos-light-wallet#24]
Add a spending password for logged in session for extra security, password will be used for every spend transaction

**Comment by coranos** [comment]
you already have to sign the transaction on the ledger, why would you need an additional password?

**Comment by MButcho** [comment]
Implemented in https://github.com/MButcho/elastos-light-wallet/releases/tag/v1.0.0-RC49-MB should be merged soon.

**Comment by TI-ZA** [comment]
added in v1.0.0
