### ISSUE TITLE
Bug: Unable to vote after voting once

### ISSUE THREAD

**Issue by zymptomLabs** [cyber-republic/elastos-light-wallet#28]
I was able to vote for 20 nodes the first time. Now I'm trying to re-vote and it won't even let me vote for 10 of the same ones I had selected previously.

![ela1](https://user-images.githubusercontent.com/17466655/88359011-5ebf3380-cd2e-11ea-96a1-03bc4d322db3.png)
![ela2](https://user-images.githubusercontent.com/17466655/88359014-61218d80-cd2e-11ea-9125-e73194559280.png)

**Comment by zymptomLabs** [comment]
If you have 1 node selected the transaction length is still too high.  If you have 0 selected you can't vote.

**Comment by MButcho** [comment]
It is the same issue as https://github.com/cyber-republic/elastos-light-wallet/issues/29. Please read my comment there.

**Comment by zymptomLabs** [comment]
> It is the same issue as #29. Please read my comment there.

Closing this issue. It seems to be resolved by @MButcho 's build on https://github.com/cyber-republic/elastos-light-wallet/issues/29
