### ISSUE TITLE
Cannot vote for 36 candidates within one transaction

### ISSUE THREAD

**Issue by andersalm** [cyber-republic/elastos-light-wallet#32]
![image](https://user-images.githubusercontent.com/2920367/103346444-4a792280-4a94-11eb-977c-9638c9ced5cf.png)

I had to reduce it to 22 candidates in order to vote successfully.

**Comment by MButcho** [comment]
It is a known issue with Ledger transaction size limitation. Unfortunately only 22 nodes are possible to vote with Ledger. There is also issue in Elastos.ELA repository https://github.com/elastos/Elastos.ELA/issues/1631 on this matter.

**Comment by MButcho** [comment]
Close the issue pls
