### ISSUE TITLE
Voter list resets selected candidates

### ISSUE THREAD

**Issue by andersalm** [cyber-republic/elastos-light-wallet#33]
While selecting what candidates to vote for, the selection will be reset if I'm too slow.

Looks like it's happening because of the producers' list automatically refreshing.

**Comment by MButcho** [comment]
Can you make a video of that behavior and send it to me? Also, which version of Elastos Light Wallet are you using?

**Comment by andersalm** [comment]
It happened the first 2 times I tried to vote. After that, I have been unable to reproduce the issue.

I Will let you know and record a video if it happens again.

**Comment by MButcho** [comment]
It should be fixed, close the issue pls
