### ISSUE TITLE
Increase UTXO consolidations number for Ledger Users

### ISSUE THREAD

**Issue by zymptomLabs** [cyber-republic/elastos-light-wallet#39]
Currently the LEDGER_UTXO_CONSOLIDATE_COUNT is set to 20. While the non-ledger users is 500. This needs to be increased in order for Ledger users to re-vote when they add more ELA to their wallet or when they want to withdraw their coins to a new wallet.

![image](https://user-images.githubusercontent.com/17466655/109437603-de0e9700-79e2-11eb-85da-76e311ccf291.png)

![image](https://user-images.githubusercontent.com/17466655/109437621-ff6f8300-79e2-11eb-91ca-514d72f609ea.png)

**Comment by MButcho** [comment]
Impossible as the Ledger doesn't support more UTXOs than 20. It would exceed max transaction size limit of 1024 Bytes by Ledger. That's why UTXO control was introduced in v1.0.4. You are pop up that function by CTRL+u (Windows/Linux) or CMD+u on Mac.

Close this issue please
