### ISSUE TITLE
Cant open Elastos Light Wallet with ledger HELP!!

### ISSUE THREAD

**Issue by HubHubx** [cyber-republic/elastos-light-wallet#43]
I see this error : 

Ledger Status:cannot open device with path IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14400000/Nano S@14400000/Nano S@0/AppleUserUSBHostHIDDevice

And I cant open my wallet with the ledger..

I have 1.0.0-RC34 installed, and a few days ago it was working!

Help and advice would be appreciated!

**Comment by MButcho** [comment]
Download latest release from https://github.com/cyber-republic/elastos-light-wallet/releases. Also, do you have Windows or Mac?
